### ISSUE TITLE
`FileEncryptionBlock` doesn't contain the `init` member

### ISSUE THREAD

**Issue by Mingun** [Roba1993/RAR#5]
According to [the original code](https://github.com/pmachapman/unrar/blob/57b5fae83d68329f86302419a2a4047ccdaee1f2/arcread.cpp#L723-L739) of the unrar utility, initialization vectors [are located](https://github.com/pmachapman/unrar/blob/57b5fae83d68329f86302419a2a4047ccdaee1f2/arcread.cpp#L553-L566) before each encrypted block (and all blocks are encrypted after occurrence of the `FileEncryptionBlock`).

`FileEncryptionBlock` (in the original that block is called CRYPT block) doesn't contain the initialization vector, so this code is wrong:
https://github.com/Roba1993/RAR/blob/954bd98fa60541002b6492ab8f95158a52a08fa1/src/extra_block.rs#L217-L222

Lines 219-220 should be removed.

**Comment by Mingun** [comment]
Nevermind. There are two similar structures -- one for entirely array encryption (when you even don't known an array structure) and one for individual files.

My initial research points to the first places in `unrar`, but that code is related to the second: https://github.com/pmachapman/unrar/blob/57b5fae83d68329f86302419a2a4047ccdaee1f2/arcread.cpp#L997-L1054

**Comment by Roba1993** [comment]
Thank you for the investigation!
What are your plans with this crate?
I personally really miss the functionality of the decompressing with the VM....

**Comment by Mingun** [comment]
Right now I plan to implement rar5 support in [junrar](https://github.com/junrar/junrar/issues/23) and gathering required information. Maybe also porting the code here because I like Rust

**Comment by Roba1993** [comment]
Nice 👍 please keep me informed.
